- name: Set Django project with heroku
  hosts: digitalocean
  tasks:
    - name: Include vars files
      include_vars: "{{PROJECT_PATH}}/.drim/vars.yml"
    - set_fact:
        datetime: "{{ansible_date_time}}"
    - name: Create backup folders if not exists
      file:
        path: "~/backups/database/{{item.database}}"
        state: directory
      with_items: "{{databases.postgresql}}"
    - name: Create dump of {{item.database}} database
      shell: "pg_dump -U {{item.database}}_admin {{item.database}} > ~/backups/database/{{item.database}}/{{datetime.iso8601}}.sql"
      with_items: "{{databases.postgresql}}"
    - name: Fetch dump of {{item.database}} just created to localhost
      fetch:
        src: "~/backups/database/{{item.database}}/{{datetime.iso8601}}.sql"
        dest: "{{PROJECT_PATH}}/.drim/backups/{{datetime.iso8601}}"
      with_items: "{{databases.postgresql}}"
